apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base/
namespace: operator-prometheus
commonAnnotations:
  catalog.kubestack.com/heritage: kubestack.com/catalog/prometheus
  catalog.kubestack.com/variant: clusterwide
  app.kubernetes.io/version: v0.36.0
resources:
- namespace.yaml
- instance-cluster-role.yaml
