apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
commonAnnotations:
  catalog.kubestack.com/heritage: kubestack.com/catalog/nginx
  catalog.kubestack.com/variant: base
  app.kubernetes.io/version: v0.26.1
commonLabels:
  app.kubernetes.io/component: ingress-controller
  app.kubernetes.io/managed-by: kubestack
  app.kubernetes.io/name: nginx
patchesStrategicMerge:
- patch-replicas.yaml
resources:
- mandatory.yaml
