name: CI

on: 
  pull_request:
    branches:
      - master

# Environment variables available to all jobs and steps in this workflow
env:
  PROJECT_ID: ${{ secrets.KBST_PROJECT }}
  RUN_REGION: europe-west4
  TERRAFORM_VERSION: 0.12.19
  GOOGLE_CLOUD_SDK_VERSION: 272.0.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # GCP steps
    - name: Authenticate to GCP
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: ${{ env.TERRAFORM_VERSION }}
        service_account_email: ${{ secrets.SA_EMAIL }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}

    # Terraform steps
    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ${{ env.TERRAFORM_VERSION }}
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: '.'
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}} 
    
    - name: 'Terraform Validate'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ${{ env.TERRAFORM_VERSION }}
        tf_actions_subcommand: 'validate'
        tf_actions_working_dir: '.'
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: 'Terraform Plan'
      id: 'terraform_plan'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ${{ env.TERRAFORM_VERSION }}
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: '.'
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
#     - name: 'Terraform Apply'
#       uses: hashicorp/terraform-github-actions@master
#       with:
#         tf_actions_version: $TERRAFORM_VERSION
#         tf_actions_subcommand: 'apply'
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
