name: CI

on: 
  pull_request:
    branches:
      - master

# Environment variables available to all jobs and steps in this workflow
env:
  PROJECT_ID: ${{ secrets.KBST_PROJECT }}
  RUN_REGION: europe-west4

jobs:
  deploy:
    runs-on: mvbakker/kbst-infra-automation:bootstrap

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # GCP steps
    - name: Authenticate to GCP
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '275.0.0'
        service_account_email: ${{ secrets.SA_EMAIL }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}

    # Terraform steps
    - name: Initialize Terraform
      run: terraform init
    - name: Create 'ops' workspace
      run: terraform workspace new ops
    - name: Plan Terraform
      run: terraform plan -out=tfplan
