name: CI

on:
  push:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    #
    #
    # Build image
    - name: Build image
      env:
        DOCKER_BUILDKIT: 1
      run: docker build -t kbst-infra-automation:bootstrap ci-cd/

    #
    #
    # Setup Gcloud credentials
    - name: Setup Gcloud credentials
      env:
        GCLOUD_AUTH: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}
      run: |
            mkdir -p .user/.config/gcloud
            echo "$GCLOUD_AUTH" | base64 --decode > .user/.config/gcloud/application_default_credentials.json
            docker run --rm -v `pwd`:/infra -u `id -u`:`id -g` kbst-infra-automation:bootstrap gcloud auth activate-service-account --key-file=/infra/.user/.config/gcloud/application_default_credentials.json

    #
    #
    # Terraform init
    - name: Terraform init
      env:
        TF_IN_AUTOMATION: true
      run: docker run --rm -t -v `pwd`:/infra -u `id -u`:`id -g` kbst-infra-automation:bootstrap terraform init

    #
    #
    # Select ops workspace
    - name: Select ops workspace
      env:
        TF_IN_AUTOMATION: true
      if: startsWith(github.ref, 'refs/tags/apps-deploy-') == false
      run: docker run --rm -t -v `pwd`:/infra -u `id -u`:`id -g` kbst-infra-automation:bootstrap terraform workspace select ops

    #
    #
    # Select apps workspace
    - name: Select apps workspace
      env:
        TF_IN_AUTOMATION: true
      if: startsWith(github.ref, 'refs/tags/apps-deploy-') || startsWith(github.ref, 'refs/tags/destroy-')
      run: docker run --rm -t -v `pwd`:/infra -u `id -u`:`id -g` kbst-infra-automation:bootstrap terraform workspace select apps

    #
    #
    # Terraform plan
    - name: Terraform plan
      env:
        TF_IN_AUTOMATION: true
      run: docker run --rm -t -v `pwd`:/infra -u `id -u`:`id -g` kbst-infra-automation:bootstrap terraform plan -out=tfplan -input=false

    #
    #
    # Terraform apply
    - name: Terraform apply
      env:
        TF_IN_AUTOMATION: true
      if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/apps-deploy-')
      run: docker run --rm -v `pwd`:/infra -u `id -u`:`id -g` kbst-infra-automation:bootstrap terraform apply -input=false tfplan

    #
    #
    # Terraform destroy apps cluster
    - name: Terraform destroy apps cluster
      env:
        TF_IN_AUTOMATION: true
      if: startsWith(github.ref, 'refs/tags/destroy-')
      run: docker run --rm -v `pwd`:/infra -u `id -u`:`id -g` kbst-infra-automation:bootstrap terraform destroy -auto-approve

    #
    #
    # Select ops workspace
    - name: Select ops workspace
      env:
        TF_IN_AUTOMATION: true
      if: startsWith(github.ref, 'refs/tags/destroy-') == false
      run: docker run --rm -t -v `pwd`:/infra -u `id -u`:`id -g` kbst-infra-automation:bootstrap terraform workspace select ops
    
    #
    #
    # Terraform destroy ops cluster
    - name: Terraform destroy ops cluster
      env:
        TF_IN_AUTOMATION: true
      if: startsWith(github.ref, 'refs/tags/destroy-')
      run: docker run --rm -v `pwd`:/infra -u `id -u`:`id -g` kbst-infra-automation:bootstrap terraform destroy -auto-approve

    #
    #
    # Terraform state list
    - name: List all resources in the state
      env:
        TF_IN_AUTOMATION: true
      run: docker run --rm -v `pwd`:/infra -u `id -u`:`id -g` kbst-infra-automation:bootstrap terraform state list